DECLARE
    CURSOR STUDENT_CURSOR IS
        SELECT ID, NAME, MARK FROM STUDENT;

    V_ID STUDENT.ID%TYPE;
    V_NAME STUDENT.NAME%TYPE;
    V_MARK STUDENT.MARK%TYPE;

BEGIN
    OPEN STUDENT_CURSOR;

    LOOP
        FETCH STUDENT_CURSOR INTO V_ID, V_NAME, V_MARK;

        EXIT WHEN STUDENT_CURSOR%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'ID: ' || V_ID ||
            '  NAME: ' || V_NAME ||
            '  MARK: ' || V_MARK
        );
    END LOOP;

    CLOSE STUDENT_CURSOR;
END;
/

